name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}
      GIT_REF: ${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run go tests
      - name: Run tests
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: make test

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build or pull image
      - name: Build image
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: make build-image

      - name: Pull image
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: make pull-image

      # Test the image
      - name: Test image
        run: make test-image

      # Push or promote image
      - name: Push image
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          make push-image

      - name: Promote image
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          make promote-image
