name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Run go tests
    - name: Run tests
      run: make test

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build or pull image
    - name: Build image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: make build-image

    - name: Pull image
      if: startsWith(github.ref, 'refs/tags/v')
      run: make pull-image

    # Test the image
    - name: Test image
      run: make test-image

    # Push or promote image
    - name: Push image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: |
        make push-image

    - name: Promote image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make promote-image GITHUB_REF=$GITHUB_REF
